# DO NOT MODIFY -- auto-generated by Apache Cordova
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!
target 'MyApp' do
	project 'MyApp.xcodeproj'
	pod 'AppCenter', '~> 2.5.0'
	pod 'AppCenter/Analytics', '~> 2.5.0'
	pod 'AppCenter/Crashes', '~> 2.5.0'
end
